name: Compile Python Packages with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install --upgrade pydub
          sudo apt install ffmpeg
      - name: Compile all Python scripts
        run: |
          pyinstaller --onefile 8d.py
      - name: Upload Linux executables
        uses: actions/upload-artifact@v4
        with:
          name: linux-executables
          path: dist/*
