name: Compile Python Packages with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compile all Python scripts
        shell: pwsh
        run: |
          Get-ChildItem -Filter *.py | ForEach-Object {
            pyinstaller --onefile $_.Name
          }
      - name: Upload each Windows executable individually
        shell: pwsh
        run: |
          Get-ChildItem -Path dist -Filter *.exe | ForEach-Object {
            $artifactName = $_.BaseName + "-windows"
            echo "Uploading $($_.FullName) as $artifactName"
            gh run upload-artifact --name $artifactName $_.FullName
          }
        env:
         GH_TOKEN: ${{ secrets.SECRET }}


  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compile all Python scripts
        run: |
          for f in *.py; do pyinstaller --onefile "$f"; done

      - name: Upload each Linux executable individually
        run: |
          for f in dist/*; do
            name="$(basename "$f")-linux"
            echo "Uploading $f as $name"
            gh run upload-artifact --name "$name" "$f"
          done
        env:
         GH_TOKEN: ${{ secrets.SECRET }}

