name: Compile and Test Python Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile banana.py, banana-video.py, and thlinh.py
        run: |
          python banana.py
          python banana-video.py
          python thlinh.py

      - name: Run tests
        run: |
          # If you have tests, you can add a testing framework like pytest
          pytest

  linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compile banana.py, banana-video.py, and thlinh.py
        run: |
          python banana.py
          python banana-video.py
          python thlinh.py

      - name: Run tests
        run: |
          pytest
